apiVersion: v1
kind: Pod
metadata:
  name: ace-server
  labels:
    app: ace
spec:
  containers:
    - name: ace
      image: moiz3388/ace13:latest
      env:
        - name: LICENSE
          value: "accept"
      ports:
        - containerPort: 7600
        - containerPort: 7800
        - containerPort: 7843
      command: ["tail", "-f", "/dev/null"]
